learning_rate: 0.0003
reward_gamma: 0.99
reward_scale: 20
alpha: 0.2

memory_capacity: 1000000
batch_size: 256

min_experience: 256
learn_loops: 5

tensorboard_events_path: "./tensorboard"
weights_path: "./weights"
memory_path: "./memory"
